# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'FMDB'
pod 'ZYCornerRadius'
pod 'SDWebImage' ,"3.8.2"
pod 'TZImagePickerController'
pod 'IQKeyboardManager'
pod 'AFNetworking'
pod 'CDDPagerController'


pod 'WechatOpenSDK'
pod 'AlipaySDK-iOS'
pod 'Meiqia', '~> 3.4.9'
target 'UNIGOStore' do


end
